### ISSUE TITLE
detect_intent doesn't work on web server

### ISSUE THREAD

**Issue by foob7** [googleapis/dialogflow-python-client-v2#115]
I am currently working with dialogflow_v2 on python 3.6.2. 

I have tried to use the detect_intent function on a web server but it keeps throwing:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 547, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1549349039.892000000","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":14}"
>

The same code works fine if run through console. Does anyone know what is causing the issue?

The code looks like this:
```
def detect_intent_texts(project_id, session_id, texts, language_code='en'):
    session_client = dialogflow_v2.SessionsClient()

    session = session_client.session_path(project_id, session_id)
    print('Session path: {}\n'.format(session))

    for text in texts:
        text_input = dialogflow_v2.types.TextInput(
            text=text, language_code=language_code)

        query_input = dialogflow_v2.types.QueryInput(text=text_input)

        response = session_client.detect_intent(
            session=session, query_input=query_input)

        print('Detected intent: {} (confidence: {})\n'.format(
            response.query_result.intent.display_name,
            response.query_result.intent_detection_confidence))


print (detect_intent_texts('test-bot-123', '1', ['test']))
```

**Comment by npreethi** [comment]
Hi, I seem to be running into the same issue. Appreciate any thoughts on how to resolve, thanks.

**Comment by npreethi** [comment]
> Hi, I seem to be running into the same issue. Appreciate any thoughts on how to resolve, thanks.

Here is the stack trace, looks similar to the report above but observed with dialogflow session (instead of dialogflow_v2 session, the rest of the code snippet is similar).

Traceback (most recent call last):
  File "/user/home/venv_3.6.6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/user/home/venv_3.6.6/lib/python3.6/site-packages/grpc/_channel.py", line 562, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/user/home/venv_3.6.6/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1555541768.247069295","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":14}"

**Comment by serranomorante** [comment]
Hi, I was facing the same issue from Windows Server+Apache+mod_wsgi. I decided to change the environment to Ubuntu Server+Nginx+Gunicorn and now is working fine. Sorry if a can't really help with the core of the problem.

**Comment by npreethi** [comment]
> Here is the stack trace, looks similar to the report above but observed with dialogflow session (instead of dialogflow_v2 session, the rest of the code snippet is similar).
> 
> <snip>

Environment:
- RedHat 7.3
- NGINX setup with Gunicorn (19.7.1) and Supervisord (3.1.4)

Python packages:
dialogflow==0.5.2
Flask==1.0.2
gevent==1.2.2
google-api-core==1.9.0
google-auth==1.6.3
googleapis-common-protos==1.5.9
greenlet==0.4.15
grpcio==1.20.0
gunicorn==19.7.1

**Comment by npreethi** [comment]
> > Here is the stack trace, looks similar to the report above but observed with dialogflow session (instead of dialogflow_v2 session, the rest of the code snippet is similar).
> 
> Environment:
> 
> * RedHat 7.3
> * NGINX setup with Gunicorn (19.7.1) and Supervisord (3.1.4)
> 
> Python packages:
> dialogflow==0.5.2
> Flask==1.0.2
> gevent==1.2.2
> google-api-core==1.9.0
> google-auth==1.6.3
> googleapis-common-protos==1.5.9
> greenlet==0.4.15
> grpcio==1.20.0
> gunicorn==19.7.1

Quick update: 
The first attempt for detect_intent() always fails and retrying detect_intent() becomes successful. Is it probably better that this retry logic is handled within the dialogflow/grpc library instead of the application level?

However, still running into the following issues, would be great if an experts here can pitch in:

- the first attempt at detect_intent() always takes a long time (order of seconds) to fail. Are there ways to reduce this latency at the GRPC end?

- Is there a recommended to perform this retry (perhaps with exponential backoff) at the application side?

**Comment by davit555** [comment]
Hey
any updates on this?

**Comment by busunkim96** [comment]
We have decorators you can apply to configure timeouts and retries.

https://googleapis.dev/python/google-api-core/latest/retry.html
https://googleapis.dev/python/google-api-core/latest/timeout.html

The behavior you mention is odd though (first request taking a long time to fail, and the subsequent one succeeding). This error is only occurring in a web server? Is there anything else interesting about your environment?

**Comment by nnegrey** [comment]
To try to pin down the issue, is your server just bare bones, running just the detect intent call to start?

**Comment by npreethi** [comment]
> To try to pin down the issue, is your server just bare bones, running just the detect intent call to start?

Yes, bare bones EC2 instance running Ubuntu. Package details as in the original post. To recap, the issue arises only via NGINX+supervisor setup not through the console.

**Comment by nnegrey** [comment]
I'm not very familiar with the inner workings of EC2, but does this page help at all?
https://cloud.google.com/solutions/using-gcp-apis-from-an-external-network

**Comment by nnegrey** [comment]
Also does it work from the AWS CLI on the EC2 instance or just your local console?

**Comment by npreethi** [comment]
> Also does it work from the AWS CLI on the EC2 instance or just your local console?

@busunkim96 @nnegrey 

The whole setup works perfect when I do "python app.py" on the EC2 (and local). I.e., the detect_intent calls go through fine at the first attempt without hitting 'deadline exceeded'. The issue arises only when run with NGINX+supervisor. I doubt if the networking/firewall is an issue here since the same setup works fine via console.

**Comment by nnegrey** [comment]
Does it work if you just run a barebones server on your local machine and not EC2? 

Then the issue is probably somewhere with NGINX+supervisor.

**Comment by hjethwa** [comment]
I was able to fix this by not using gevent as --worker-class for gunicorn. There is an issue with grpc when that is enabled.

**Comment by manumnair** [comment]
@hjethwa Could you explain a bit more please. I am using python Flask to host as an API. Apache is the webserver. detect_intent gets timed out after 300 seconds. No response is received
