### ISSUE TITLE
Add the actual default values for parameters to the docs

### ISSUE THREAD

**Issue by Syndace** [googleapis/dialogflow-python-client-v2#173]
The documentation talks about default values for the `timeout` and `retry` parameters in various places, but it doesn't state what these defaults actually are. I think I found them in `gapic/agents_client_config.py`, but I'd much prefer to have them included in the documentation.

**Comment by nnegrey** [comment]
@busunkim96, this sounds like something to look at in our auto-generation tools or is there just something not properly configured?

**Comment by busunkim96** [comment]
Those are the standard docstrings for retry and timeout. Example: https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/api.html#dialogflow_v2.EntityTypesClient.list_entity_types

Default values are indeed in https://github.com/googleapis/dialogflow-python-client-v2/blob/master/dialogflow_v2beta1/gapic/agents_client_config.py as @Syndace pointed out.

It might be possible to pull in the specific values but I don't think it would be trivial, since it varies by method. (An easier band-aid would be to mention the config file so folks know where to look) I can file a feature request on the generator if there is interest.

**Comment by czahedi** [comment]
I'm cool with your bandaid solution of pointing to this source unless you worry the links are going to change regularly enough to render that frustrating to maintain

**Comment by nnegrey** [comment]
I'd put it as a lower priority, though I think I would rather have us put out some official documentation as to how to configure retries and timeouts in a canonical format. 

Closing.
