### ISSUE TITLE
How can I list/query all the already registered TrainingPhrases for a fiven intent

### ISSUE THREAD

**Issue by rsilveira79** [googleapis/dialogflow-python-client-v2#23]
Hello, I'm testing _dialogflow_v2beta1_ and I want to query all the intent phrases (text only - userSays) for a given intent. I found the class (dialogflow_v2beta1.types.Intent.TrainingPhrase()) but haven't found a clear way to get UserSays phrases from that. Thanks!

**Comment by Luttik** [comment]
Im wondering the same. It is strange that this important issue has been unattended to for so long.

**Comment by dysnomia** [comment]
Generally: By default the training_phrases aren't returned because they can be very big. You need to explicitly set intent_view to INTENT_VIEW_FULL when getting the intent  (https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2beta1/IntentView in http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/api.html#dialogflow_v2.IntentsClient.get_intent).

In the returned `TrainingPhrase` the UserSays are in `parts` collection (http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.Intent.TrainingPhrase.parts). 

Unfortunately `parts` may have a complex structure for annotated examples (http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.Intent.TrainingPhrase.Part). For example `language en` where `en` is annotated with entity `@language` may be returned as (in JSON):

```
{
  "name": "...",
  "type": EXAMPLE,
  "parts": [
    {
      "text": "language ",
    },
    {
      "text": "en",
      "entityType": "@language",
      "alias": "language",
      "userDefined": true
    }
  ]
}
```

Please let me know whether that helps!
