### ISSUE TITLE
Ability to convert elements to more basic data structures (FeatureRequest)

### ISSUE THREAD

**Issue by Luttik** [googleapis/dialogflow-python-client-v2#63]
(NOTE: for those looking for the answer look into from [google.protobuf.json_format.MessageToDict](https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py))

I use `SessionsClient.detect_intent` to communicate with dialogflow. But if you like me need to analyse the custom payload by digging into `query_result` you find that it uses a non-trivial, barely documented datastructure. 

I would like a way to convert this structure into pythons standard data types (enabling things like quick serialisation and analysis with less code).

I currently do it with this code:
```
def parse_messages(x):
    if isinstance(x, RepeatedCompositeFieldContainer) or isinstance(x, RepeatedScalarFieldContainer) \
            or isinstance(x, ListValue):
        return list([parse_messages(y) for y in list(x)])
    if isinstance(x, Value):
        return parse_messages(x.ListFields()[0][1])
    if isinstance(x, Struct):
        return parse_messages(x.fields)
    if isinstance(x, Message):
        return {y[0].name: parse_messages(y[1]) for y in x.ListFields()}
    if isinstance(x, MessageMap):
        return {y: parse_messages(z) for y, z in x.items()}
    return x
```
But I don't know if this is secure or wise. Also since I expect the response format from the server to be json it is overly complex to first convert it to the complex data type and afterwards having to convert it back.

I understand that this might not have the highest priority but I do believe it would greatly improve the usability of the library if elements like this were build in.

**Comment by dysnomia** [comment]
Yeah, this shared protobuf type only has very basic documentation at https://developers.google.com/protocol-buffers/docs/reference/python-generated#struct. There are some more usage examples https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py#L683.

About converting to/from Python types:

- From dict: update seems to directly convert from a dict to a struct: https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py#L818.
- To dict: As far as I can see, there is no direct support for that. But Struct implements (almost) the same interface as dict (https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py#L727). Can you just use it in place of dict instead of converting? For serialization: Can you use the proto serialization (https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py#L715)?

I'll file a bug to improve our shared documentation.

**Comment by Luttik** [comment]
So serialization works for instance for converting to string, but ToJsonString for instance is not implemented on all objects.

And for instance a Message object does not implement .items(), for that you need to use ListFields() which works slightly different. 

I keep running into errors because different object types are used in unexpected places (and a seemingly inconsistent fashion), and I need to convert these elements before i can do something like sending the dialogflow payload to the frontend.

**Comment by Luttik** [comment]
I found the following solution:

```
from google.protobuf.json_format import MessageToDict

result: DetectIntentResponse = detect_intent_texts([request_text], int(session_token, 16), agent_id)
messages = [MessageToDict(x) for x in result.query_result.fulfillment_messages]
```

This method seems works great it is just hard to find in the documentation.

@dysnomia Thanks for you assistance.

**Comment by nnegrey** [comment]
This appears to be answered, if not, please feel free to re-open.

Thanks! :)
